import funGenerales

# -------- LO QUE ME FALTA HACER -----------------

# FALTA AGREGAR EN LA FUN DE PARTIDA NUEVA LO DE CONTINUAR ENTRE MEDIO DE LA JUGADA
# YA ESTA AGREGADA EN LO DE REANUDAR

# PROGRAMAR EMPATES CON LA LISTA QUE DIJO NICO

# SI SOBRA TIEMPO HACER LO DE QUE AL ANOTAR NADA ESPECIAL O TACHAR TE MUESTRE QUÉ ES LO QUE PODES ANOTAR/TACHAR

# SI SOBRA TIEMPO HACER UN SCORE DE GANADORES
# TIPO UNA TABLA DE POSICIONES CON LA SUMA DE LOS PUNTOS ACUMULADOS AL GANAR UNA PARTIDA.

# ------------------------------------------------

funGenerales.iniciarPrograma()
